[profile.default]
libs = ["dependencies"]
auto_detect_remappings = false
solc = "0.8.35"
evm_version = "osaka"
ignored_warnings_from = ["dependencies"]
ignored_error_codes = [2424]
remappings = [
    "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.6.1/",
    "@openzeppelin/contracts-upgradeable/=dependencies/@openzeppelin-contracts-upgradeable-5.6.1/",
    "forge-std/=dependencies/forge-std-1.16.1/src/",
    "openzeppelin-foundry-upgrades/=dependencies/openzeppelin-foundry-upgrades-0.4.0/src/",
    "@common/=common/src/",
]

[soldeer]
remappings_generate = false
remappings_regenerate = false
remappings_version = true
remappings_prefix = ""
remappings_location = "config"
recursive_deps = false

[fmt]
line_length = 100
number_underscore = "thousands"
ignore = [
    "**/node_modules/**",
    "**/artifacts/**",
    "**/cache/**",
    "**/lib/**",
    "**/dependencies/**"
]

[dependencies]
forge-std = "1.16.1"
"@openzeppelin-contracts" = "5.6.1"
"@openzeppelin-contracts-upgradeable" = "5.6.1"
openzeppelin-foundry-upgrades = "0.4.0"

[rpc_endpoints]
ethereum = "${ETHEREUM_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
hoodi = "${HOODI_RPC_URL}"
base = "${BASE_RPC_URL}"
base-sepolia = "${BASE_SEPOLIA_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
optimism-sepolia = "${OPTIMISM_SEPOLIA_RPC_URL}"

[etherscan]
ethereum = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/api", chain = 1 }
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api", chain = 11155111 }
hoodi = { key = "${ETHERSCAN_API_KEY}", url = "https://hoodi.etherscan.io/api", chain = 560048 }
base = { key = "${ETHERSCAN_API_KEY}", url = "https://api.basescan.org/api", chain = 8453 }
base-sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api", chain = 84532 }
optimism = { key = "${OPTIMISTIC_ETHERSCAN_API_KEY}", url = "https://api-optimistic.etherscan.io/api", chain = 10 }
optimism-sepolia = { key = "${OPTIMISTIC_ETHERSCAN_API_KEY}", url = "https://api-sepolia-optimistic.etherscan.io/api", chain = 11155420 }
