name: Allow only develop to master

on:
  pull_request:
    branches:
      - master

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR source is not develop
        run: |
          echo "base_ref=${{ github.base_ref }}"
          echo "head_ref=${{ github.head_ref }}"

          if [ "${{ github.head_ref }}" != "develop" ]; then
            echo "Only pull requests from 'develop' to 'master' are allowed."
            exit 1
          fi
